---
- name: Install nginx
  apt: name=nginx state=present

- name: Copy nginx configuration
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: stat foo
  stat: path=/etc/nginx/sites-enabled/default
  register: def_stat

- name: Rename default file
  command: mv /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default.old
  when: def_stat.stat.exists

- name: ==> add PPA of php7 (community)
  apt_repository: repo="ppa:ondrej/php"

- name: ==> download/update the package lists
  apt: update_cache=yes

- name: ==> install php-fpm, and php-mysql (php7.0)
  apt: name={{ item }} state=present
  with_items:
    - php7.0-fpm
    - php7.0-mysql
- name: fix listen.group for php-fpm
  lineinfile:
    dest: /etc/php/7.0/fpm/pool.d/www.conf
    regexp: '^listen.group\s*=.*$'
    line: "listen.group=www-data"
    state: present
  notify: restart php-fpm

- name: fix user for php-fpm
  lineinfile:
    dest: /etc/php/7.0/fpm/pool.d/www.conf
    regexp: '^user\s*=.*$'
    line: "user = www-data"
    state: present
  notify: restart php-fpm

- name: fix group for php-fpm
  lineinfile:
    dest: /etc/php/7.0/fpm/pool.d/www.conf
    regexp: '^group\s*=.*$'
    line: "group = www-data"
    state: present
  notify: restart php-fpm
