---
- name: Install nginx
  apt: name=nginx state=present

- name: Copy nginx configuration
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
- name: Rename default file
  command: mv /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default.old