---

- name: Configuration commune
  hosts: all
  remote_user: root
 # remote_user: user
 # become: yes
 # become_method: sudo

  roles:
    - common
    - fail2ban


- name: Install Nginx
  hosts: nginx 
  remote_user: root
 # remote_user: user
 # become: yes
 # become_method: sudo

  roles:
    - nginx


