---

- name: Configuration commune
  hosts: all
  remote_user: root
 # remote_user: user
 # become: yes
 # become_method: sudo

  roles:
    - common



- name: Install Nginx
  hosts: web
  remote_user: root
 # remote_user: user
 # become: yes
 # become_method: sudo

  roles:
    - nginx


