---

- name: Include OS-specific variables
  include_vars: "ubuntu.yml"


- name: add git, zsh, vim, htop
  apt: pkg={{ item }} state=latest update_cache=true
  with_items:
     - htop
     - zsh
     - vim
     - pigz
     - wget 
  sudo: yes

- name: install oh-my-zsh
  shell: wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O - | sh 
- name: Copy zshrc
  template: src=zshrc dest=/root/.zshrc
